# Generated by Django 5.1.7 on 2025-03-22 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_market', '0001_initial'),
        ('stock_portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('VOLATILITY', 'High Volatility'), ('CONCENTRATION', 'Portfolio Concentration'), ('DRAWDOWN', 'Significant Drawdown'), ('CORRELATION', 'High Correlation')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_portfolio.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=6)),
                ('volatility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diversification_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sharpe_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.TextField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_portfolio.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockRiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volatility', models.DecimalField(decimal_places=2, max_digits=5)),
                ('var_95', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock_market.stock')),
            ],
        ),
    ]
